import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { getUser } from "@/lib/auth";
import AdminGuard from "@/widget/admin/AdminGuard";
import Header from "@/widget/public/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const AdminLayout = async ({ children }: { children: React.ReactNode }) => {
    const user = await getUser();

    return (
        <>
            <Header headerType="admin" user={user} />
            <main className="container mx-auto px-4 py-8">
                {children}
            </main>
        </>
    );
};

export default AdminLayout;